FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Clear npm cache and install dependencies
RUN npm cache clean --force && \
    npm install --verbose

RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]